spring.application.name=dynamodb-demo

spring.datasource.url=jdbc:h2:mem:employees-local;MODE=PostgreSQL;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.h2.console.enabled=true

app.dynamodb.table-name=EmployeeTable
