package com.example.agent;

import java.nio.file.Path;
import java.nio.file.Files;
import java.util.ArrayList;
import java.util.List;
import java.util.Locale;

public final class JavaOrchestratorAgent {

    private JavaOrchestratorAgent() {
    }

    public static void main(String[] args) throws Exception {
        System.exit(execute(args));
    }

    public static int execute(String[] args) throws Exception {
        AgentArgs parsed = AgentArgs.parse(args);
        String configPath = parsed.get("config", AgentConfig.defaultConfigPath().toString());
        AgentConfig config = AgentConfig.load(Path.of(configPath).toAbsolutePath().normalize());
        Path projectDir = Path.of(parsed.get("project-dir", "../dynamodb-demo")).toAbsolutePath().normalize();
        Path repoDir = Path.of(parsed.get("repo-dir", "..")).toAbsolutePath().normalize();
        String region = parsed.get("region", "us-east-1");
        String cluster = parsed.get("cluster", "dynamodb-demo-cluster");
        String service = parsed.get("service", "dynamodb-demo-service");
        String auditTable = parsed.get("audit-table", "AgentAudit");
        String baseUrl = parsed.get("base-url", "");
        String emailMode = parsed.get("email-mode", "auto");
        List<String> paths = parsed.list("paths",
                List.of("dynamodb-demo/src/main/java/com/example/dynamodb_demo/model/Employee.java"));
        boolean dryRun = parsed.has("dry-run");

        System.out.printf("[%s] Starting Java coordinated agent workflow%n", AgentSupport.utcNow());
        printApprovalReadiness(emailMode);

        boolean monitorFoundBug = false;
        if (parsed.has("skip-monitor")) {
            System.out.println("ECS monitor skipped.");
        } else {
            List<String> monitorArgs = new ArrayList<>(List.of(
                    "--region", region,
                    "--cluster", cluster,
                    "--service", service,
                    "--audit-table", auditTable,
                    "--fail-on-bug"));
            if (dryRun) {
                monitorArgs.add("--dry-run");
            }
            int monitorExit = JavaEcsMonitorAgent.execute(monitorArgs.toArray(String[]::new));
            if (monitorExit == 1) {
                monitorFoundBug = true;
                System.out.println("ECS monitor found at least one finding.");
            } else if (monitorExit != 0) {
                throw new IllegalStateException("Java ECS monitor failed with exit code " + monitorExit);
            }
        }

        if (!baseUrl.isBlank()) {
            System.out.println("Using deployed app URL for validation smoke check: " + baseUrl);
        }

        List<String> missingRuleNames = missingValidationRuleNames(projectDir, config.rules());
        if (!missingRuleNames.isEmpty()) {
            System.out.println("Missing configured validation rules: " + String.join(", ", missingRuleNames));
        }

        List<String> fixArgs = new ArrayList<>(List.of(
                "--config", configPath,
                "--project-dir", projectDir.toString(),
                "--region", region,
                "--audit-table", auditTable));
        if (!baseUrl.isBlank()) {
            fixArgs.add("--base-url");
            fixArgs.add(baseUrl);
        }
        if (dryRun) {
            fixArgs.add("--dry-run");
        }
        int fixExit = JavaAutoFixAgent.execute(fixArgs.toArray(String[]::new));
        if (fixExit != 0) {
            throw new IllegalStateException("Java auto-fix agent failed with exit code " + fixExit);
        }

        if (!JavaPrApprovalAgent.hasChanges(repoDir, paths)) {
            if (monitorFoundBug) {
                System.out.println("Monitor found a bug, but no configured source files changed. No PR was created.");
                return 1;
            }
            System.out.println("No source changes were produced. No PR/email approval is needed.");
            return 0;
        }

        System.out.println("Source changes detected. Creating approval PR and notification.");
        String ruleSummary = missingRuleNames.isEmpty() ? "configured validation rule" : String.join(", ", missingRuleNames);
        String branch = parsed.get("fix-branch", defaultFixBranch(missingRuleNames));
        List<String> prArgs = new ArrayList<>(List.of(
                "--repo-dir", repoDir.toString(),
                "--base-branch", parsed.get("base-branch", "main"),
                "--remote", parsed.get("remote", "origin"),
                "--branch", branch,
                "--commit-message", parsed.get("commit-message", "fix: apply agent-generated bug fix"),
                "--pr-title", parsed.get("pr-title", "Agent fix: " + ruleSummary),
                "--pr-body", parsed.get("pr-body", "This PR was generated by the Java coordinated agent workflow for: " + ruleSummary + ". It is waiting for human approval."),
                "--project-name", parsed.get("project-name", "springboot-dynamodb-project"),
                "--summary", parsed.get("summary", "The Java monitor/auto-fix workflow generated a bug fix for: " + ruleSummary + "."),
                "--email-subject", parsed.get("email-subject", "Human approval requested for agent bug fix"),
                "--email-mode", emailMode,
                "--outbox-file", parsed.get("outbox-file", "build/approval-email.txt"),
                "--region", region,
                "--audit-table", auditTable));
        String githubRepo = parsed.get("github-repo", "");
        if (!githubRepo.isBlank()) {
            prArgs.add("--github-repo");
            prArgs.add(githubRepo);
        }
        if (!paths.isEmpty()) {
            prArgs.add("--paths");
            prArgs.addAll(paths);
        }
        if (dryRun) {
            prArgs.add("--dry-run");
        }
        JavaPrApprovalAgent.execute(prArgs.toArray(String[]::new));
        System.out.println("Java agent workflow completed. Human approval is now required before deployment.");
        return 0;
    }

    private static void printApprovalReadiness(String emailMode) {
        List<String> missing = new ArrayList<>();
        if (env("GITHUB_TOKEN").isBlank() && env("GH_TOKEN").isBlank()) {
            missing.add("GITHUB_TOKEN or GH_TOKEN");
        }
        if ("smtp".equals(emailMode)) {
            for (String name : List.of("APPROVAL_EMAIL_TO", "SMTP_HOST", "SMTP_USERNAME", "SMTP_PASSWORD")) {
                if (env(name).isBlank()) {
                    missing.add(name);
                }
            }
            if (env("EMAIL_FROM").isBlank() && env("SMTP_USERNAME").isBlank()) {
                missing.add("EMAIL_FROM or SMTP_USERNAME");
            }
        }
        if (!missing.isEmpty()) {
            System.out.println("Real PR/email approval is not fully configured.");
            System.out.println("Missing: " + String.join(", ", missing));
            System.out.println("The workflow can still create previews/manual PR instructions unless --email-mode smtp requires email.");
        }
    }

    private static String env(String name) {
        String value = System.getenv(name);
        return value == null ? "" : value;
    }

    private static List<String> missingValidationRuleNames(Path projectDir, List<AgentConfig.ValidationRule> rules) throws Exception {
        List<String> missing = new ArrayList<>();
        for (AgentConfig.ValidationRule rule : rules) {
            if (!"java-field-annotation".equals(rule.type())) {
                continue;
            }
            Path file = projectDir.resolve(rule.file()).normalize();
            String source = Files.readString(file);
            if (!containsAnnotation(source, rule.annotation())) {
                missing.add(rule.name());
            }
        }
        return missing;
    }

    private static boolean containsAnnotation(String source, String annotation) {
        return normalizeAnnotation(source).contains(normalizeAnnotation(annotation));
    }

    private static String normalizeAnnotation(String value) {
        return value.replaceAll("\\s+", "");
    }

    private static String defaultFixBranch(List<String> missingRuleNames) {
        if (missingRuleNames.isEmpty()) {
            return "agent-fix-configured-validation";
        }
        return "agent-fix-" + slug(String.join("-", missingRuleNames));
    }

    private static String slug(String value) {
        String slug = value.toLowerCase(Locale.ROOT).replaceAll("[^a-z0-9]+", "-");
        slug = slug.replaceAll("^-+", "").replaceAll("-+$", "");
        return slug.isBlank() ? "configured-validation" : slug;
    }
}
