package com.example.agent;

import jakarta.mail.Message;
import jakarta.mail.MessagingException;
import jakarta.mail.PasswordAuthentication;
import jakarta.mail.Session;
import jakarta.mail.Transport;
import jakarta.mail.internet.InternetAddress;
import jakarta.mail.internet.MimeMessage;
import java.io.IOException;
import java.net.URI;
import java.net.URLEncoder;
import java.net.http.HttpClient;
import java.net.http.HttpRequest;
import java.net.http.HttpResponse;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.time.Instant;
import java.time.ZoneOffset;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import java.util.List;
import java.util.Properties;
import java.util.regex.Matcher;
import java.util.regex.Pattern;

public final class JavaPrApprovalAgent {

    private static final Pattern GITHUB_REMOTE =
            Pattern.compile("github\\.com[:/]([^/]+)/([^/.]+)(?:\\.git)?$");
    private static final Pattern HTML_URL = Pattern.compile("\"html_url\"\\s*:\\s*\"([^\"]+)\"");

    private JavaPrApprovalAgent() {
    }

    public static void main(String[] args) throws Exception {
        System.exit(execute(args));
    }

    public static int execute(String[] args) throws Exception {
        AgentArgs parsed = AgentArgs.parse(args);
        Path repoDir = Path.of(parsed.get("repo-dir", "..")).toAbsolutePath().normalize();
        String branch = parsed.get("branch", defaultBranch());
        String baseBranch = parsed.get("base-branch", "main");
        String remote = parsed.get("remote", "origin");
        String region = parsed.get("region", "us-east-1");
        String auditTable = parsed.get("audit-table", "AgentAudit");
        String commitMessage = parsed.get("commit-message", "fix: apply agent-generated bug fix");
        String prTitle = parsed.get("pr-title", "Agent generated bug fix");
        String prBody = parsed.get("pr-body", "This PR was generated by the Java auto-fix agent and is waiting for human approval.");
        String projectName = parsed.get("project-name", "springboot-dynamodb-project");
        String summary = parsed.get("summary", "The Java agent generated a bug fix and requests human approval.");
        String emailSubject = parsed.get("email-subject", "Human approval requested for agent bug fix");
        String emailMode = parsed.get("email-mode", "auto");
        String outboxFile = parsed.get("outbox-file", "build/approval-email.txt");
        List<String> paths = parsed.list("paths", List.of());
        boolean dryRun = parsed.has("dry-run");
        boolean skipAudit = parsed.has("skip-audit");

        System.out.printf("[%s] Java PR approval agent preparing branch %s%n", AgentSupport.utcNow(), branch);

        GitHubRepo repo = resolveGitHubRepo(repoDir, remote, parsed.get("github-repo", ""));
        String token = env("GITHUB_TOKEN", env("GH_TOKEN", "")).trim();
        if (!dryRun && !token.isBlank()) {
            String existingPr = findExistingPrOptional(repo, branch, baseBranch, token);
            if (!existingPr.isBlank()) {
                System.out.println("Existing open PR found, not creating duplicate: " + existingPr);
                if (hasMergeConflict(repoDir, remote, baseBranch, branch)) {
                    String conflictSummary = """
                            Existing agent PR has merge conflicts and needs human resolution before approval.

                            Existing PR:
                            %s

                            Base branch:
                            %s

                            Fix branch:
                            %s
                            """.formatted(existingPr, baseBranch, branch);
                    System.out.println("Merge conflict detected for existing PR. Human action required: " + existingPr);
                    audit(region, auditTable, "PR_MERGE_CONFLICT_DETECTED", "HUMAN_ACTION_REQUIRED",
                            conflictSummary, existingPr, skipAudit);
                    boolean emailSent = sendEmail("Manual conflict resolution required for agent bug fix",
                            emailBody(projectName, existingPr, conflictSummary), emailMode, false, repoDir.resolve(outboxFile));
                    audit(region, auditTable,
                            emailSent ? "EMAIL_NOTIFICATION_SENT" : "EMAIL_NOTIFICATION_PREPARED",
                            emailSent ? "SENT" : "SMTP_CONFIGURATION_REQUIRED",
                            "Human conflict notification " + (emailSent ? "sent" : "prepared") + " for existing PR " + existingPr,
                            existingPr,
                            skipAudit);
                    return 0;
                }
                audit(region, auditTable, "PR_REUSED", "WAITING_FOR_HUMAN_APPROVAL", existingPr, existingPr, skipAudit);
                String body = emailBody(projectName, existingPr, summary);
                boolean emailSent = sendEmail(emailSubject, body, emailMode, false, repoDir.resolve(outboxFile));
                audit(region, auditTable,
                        emailSent ? "EMAIL_NOTIFICATION_SENT" : "EMAIL_NOTIFICATION_PREPARED",
                        emailSent ? "SENT" : "SMTP_CONFIGURATION_REQUIRED",
                        "Human approval notification " + (emailSent ? "sent" : "prepared") + " for existing PR " + existingPr,
                        existingPr,
                        skipAudit);
                return 0;
            }
        }

        branch = ensureBranch(repoDir, branch, dryRun);
        boolean committed = commitChanges(repoDir, paths, commitMessage, dryRun);
        pushBranch(repoDir, remote, repo, token, branch, dryRun);
        String prUrl;
        if (dryRun) {
            prUrl = fallbackPrUrl(repo, branch);
            System.out.printf("Dry-run: would create PR %s -> %s: %s%n", branch, baseBranch, prUrl);
        } else if (!token.isBlank()) {
            prUrl = createGithubPr(repo, branch, baseBranch, prTitle, prBody, token);
            System.out.println("Pull request ready: " + prUrl);
            audit(region, auditTable, "PR_CREATED", "WAITING_FOR_HUMAN_APPROVAL", prUrl, prUrl, skipAudit);
        } else {
            prUrl = fallbackPrUrl(repo, branch);
            System.out.println("GITHUB_TOKEN/GH_TOKEN is not set, so the Java agent could not create the PR through the API.");
            System.out.println("Manual PR URL: " + prUrl);
            audit(region, auditTable, "PR_CREATION_NEEDS_TOKEN", "ACTION_REQUIRED",
                    "Set GITHUB_TOKEN/GH_TOKEN or create PR manually: " + prUrl, prUrl, skipAudit || dryRun);
        }

        String body = emailBody(projectName, prUrl, summary);
        boolean emailSent = sendEmail(emailSubject, body, emailMode, dryRun, repoDir.resolve(outboxFile));
        audit(region, auditTable,
                emailSent ? "EMAIL_NOTIFICATION_SENT" : "EMAIL_NOTIFICATION_PREPARED",
                emailSent ? "SENT" : "SMTP_CONFIGURATION_REQUIRED",
                "Human approval notification " + (emailSent ? "sent" : "prepared") + " for " + prUrl,
                prUrl,
                skipAudit || dryRun);

        if (committed) {
            audit(region, auditTable, "FIX_COMMITTED_FOR_APPROVAL", "WAITING_FOR_HUMAN_APPROVAL",
                    "Committed fix branch " + branch, branch, skipAudit || dryRun);
        }
        return 0;
    }

    private static String ensureBranch(Path repoDir, String branch, boolean dryRun) throws IOException, InterruptedException {
        String current = run(repoDir, "git", "branch", "--show-current").stdout().trim();
        if (current.equals(branch)) {
            return branch;
        }
        if (dryRun) {
            System.out.println("Dry-run: would create/switch to branch " + branch);
            return branch;
        }
        String existing = run(repoDir, "git", "branch", "--list", branch).stdout().trim();
        if (existing.isBlank()) {
            run(repoDir, "git", "switch", "-c", branch);
            return branch;
        } else if (hasChanges(repoDir, List.of())) {
            String uniqueBranch = uniqueBranchName(branch);
            System.out.println("Fix branch already exists, creating unique branch for this generated fix: " + uniqueBranch);
            run(repoDir, "git", "switch", "-c", uniqueBranch);
            return uniqueBranch;
        } else {
            run(repoDir, "git", "switch", branch);
            return branch;
        }
    }

    private static String uniqueBranchName(String branch) {
        String buildNumber = env("BUILD_NUMBER", "").trim();
        if (!buildNumber.isBlank()) {
            return branch + "-build-" + buildNumber;
        }
        String timestamp = DateTimeFormatter.ofPattern("yyyyMMddHHmmss")
                .withZone(ZoneOffset.UTC)
                .format(Instant.now());
        return branch + "-" + timestamp;
    }

    private static boolean commitChanges(Path repoDir, List<String> paths, String message, boolean dryRun)
            throws IOException, InterruptedException {
        if (!hasChanges(repoDir, paths)) {
            System.out.println("No local changes to commit for the requested path set.");
            return false;
        }
        if (dryRun) {
            System.out.println("Dry-run: would stage and commit: " + message);
            return true;
        }
        List<String> add = new ArrayList<>(List.of("git", "add"));
        if (paths.isEmpty()) {
            add.add("-A");
        } else {
            add.addAll(paths);
        }
        AgentSupport.run(repoDir, add, true);
        String staged = run(repoDir, "git", "diff", "--cached", "--name-only").stdout().trim();
        if (staged.isBlank()) {
            System.out.println("No staged changes to commit.");
            return false;
        }
        ensureGitIdentity(repoDir);
        run(repoDir, "git", "commit", "-m", message);
        return true;
    }

    private static void ensureGitIdentity(Path repoDir) throws IOException, InterruptedException {
        String email = AgentSupport.run(repoDir, List.of("git", "config", "--get", "user.email"), false).stdout().trim();
        if (email.isBlank()) {
            run(repoDir, "git", "config", "user.email", env("GIT_AUTHOR_EMAIL", "agent@example.com"));
        }
        String name = AgentSupport.run(repoDir, List.of("git", "config", "--get", "user.name"), false).stdout().trim();
        if (name.isBlank()) {
            run(repoDir, "git", "config", "user.name", env("GIT_AUTHOR_NAME", "Java Agent Runner"));
        }
    }

    static boolean hasChanges(Path repoDir, List<String> paths) throws IOException, InterruptedException {
        List<String> command = new ArrayList<>(List.of("git", "status", "--porcelain"));
        if (!paths.isEmpty()) {
            command.add("--");
            command.addAll(paths);
        }
        return !AgentSupport.run(repoDir, command, true).stdout().trim().isBlank();
    }

    private static void pushBranch(Path repoDir, String remote, GitHubRepo repo, String token, String branch, boolean dryRun)
            throws IOException, InterruptedException {
        if (dryRun) {
            System.out.printf("Dry-run: would push %s to %s%n", branch, remote);
            return;
        }
        if (token.isBlank()) {
            run(repoDir, "git", "push", "-u", remote, branch);
            return;
        }
        String authenticatedRemote = "https://x-access-token:%s@github.com/%s/%s.git"
                .formatted(urlEncodeToken(token), repo.owner(), repo.name());
        run(repoDir, "git", "push", "-u", authenticatedRemote, branch);
    }

    private static GitHubRepo resolveGitHubRepo(Path repoDir, String remote, String explicit)
            throws IOException, InterruptedException {
        if (!explicit.isBlank()) {
            String[] parts = explicit.split("/", 2);
            return new GitHubRepo(parts[0], parts[1]);
        }
        String remoteUrl = run(repoDir, "git", "remote", "get-url", remote).stdout().trim();
        Matcher matcher = GITHUB_REMOTE.matcher(remoteUrl);
        if (!matcher.find()) {
            throw new IllegalStateException("Could not parse GitHub owner/repo from remote URL: " + remoteUrl);
        }
        return new GitHubRepo(matcher.group(1), matcher.group(2));
    }

    private static String createGithubPr(GitHubRepo repo, String head, String base, String title, String body, String token)
            throws IOException, InterruptedException {
        String payload = """
                {"title":%s,"head":%s,"base":%s,"body":%s}
                """.formatted(json(title), json(head), json(base), json(body));
        HttpRequest request = HttpRequest.newBuilder()
                .uri(URI.create("https://api.github.com/repos/%s/%s/pulls".formatted(repo.owner(), repo.name())))
                .header("Accept", "application/vnd.github+json")
                .header("Authorization", "Bearer " + token)
                .header("Content-Type", "application/json")
                .header("User-Agent", "springboot-dynamodb-java-pr-approval-agent")
                .POST(HttpRequest.BodyPublishers.ofString(payload))
                .build();
        HttpResponse<String> response = HttpClient.newHttpClient().send(request, HttpResponse.BodyHandlers.ofString());
        if (response.statusCode() == 201) {
            return htmlUrl(response.body());
        }
        if (response.statusCode() == 422 && response.body().toLowerCase().contains("pull request already exists")) {
            String existingPr = findExistingPrOptional(repo, head, base, token);
            if (!existingPr.isBlank()) {
                return existingPr;
            }
        }
        throw new IllegalStateException("GitHub PR creation failed HTTP " + response.statusCode() + ": " + response.body());
    }

    private static String findExistingPrOptional(GitHubRepo repo, String head, String base, String token)
            throws IOException, InterruptedException {
        String query = "head=" + encode(repo.owner() + ":" + head) + "&base=" + encode(base) + "&state=open";
        HttpRequest request = HttpRequest.newBuilder()
                .uri(URI.create("https://api.github.com/repos/%s/%s/pulls?%s".formatted(repo.owner(), repo.name(), query)))
                .header("Accept", "application/vnd.github+json")
                .header("Authorization", "Bearer " + token)
                .header("User-Agent", "springboot-dynamodb-java-pr-approval-agent")
                .GET()
                .build();
        HttpResponse<String> response = HttpClient.newHttpClient().send(request, HttpResponse.BodyHandlers.ofString());
        if (response.statusCode() != 200) {
            throw new IllegalStateException("GitHub existing PR lookup failed HTTP " + response.statusCode() + ": " + response.body());
        }
        Matcher matcher = HTML_URL.matcher(response.body());
        return matcher.find() ? matcher.group(1).replace("\\/", "/") : "";
    }

    private static boolean hasMergeConflict(Path repoDir, String remote, String baseBranch, String branch)
            throws IOException, InterruptedException {
        AgentSupport.CommandResult fetchBase = AgentSupport.run(repoDir,
                List.of(
                        "git",
                        "fetch",
                        remote,
                        "+refs/heads/%s:refs/remotes/%s/%s".formatted(baseBranch, remote, baseBranch),
                        "+refs/heads/%s:refs/remotes/%s/%s".formatted(branch, remote, branch)),
                false);
        if (fetchBase.exitCode() != 0) {
            String detail = fetchBase.stderr().isBlank() ? fetchBase.stdout() : fetchBase.stderr();
            throw new IllegalStateException("Could not fetch branches for merge conflict check: " + detail.trim());
        }

        String baseRef = "refs/remotes/%s/%s".formatted(remote, baseBranch);
        String branchRef = "refs/remotes/%s/%s".formatted(remote, branch);
        AgentSupport.CommandResult mergeCheck = AgentSupport.run(repoDir,
                List.of("git", "merge-tree", "--write-tree", baseRef, branchRef), false);
        if (mergeCheck.exitCode() == 0) {
            System.out.println("Existing PR branch can merge cleanly with " + baseBranch + ".");
            return false;
        }
        System.out.println("Merge conflict check failed: "
                + (mergeCheck.stderr().isBlank() ? mergeCheck.stdout().trim() : mergeCheck.stderr().trim()));
        return true;
    }

    private static boolean sendEmail(String subject, String body, String mode, boolean dryRun, Path outbox)
            throws IOException, MessagingException {
        String to = env("APPROVAL_EMAIL_TO", "").trim();
        String from = env("EMAIL_FROM", env("SMTP_USERNAME", "")).trim();
        String host = env("SMTP_HOST", "").trim();
        String port = env("SMTP_PORT", "587").trim();
        String username = env("SMTP_USERNAME", "").trim();
        String password = env("SMTP_PASSWORD", "");

        boolean smtpReady = !to.isBlank() && !from.isBlank() && !host.isBlank();
        if ("smtp".equals(mode) && !smtpReady) {
            throw new IllegalStateException("SMTP email is required but not configured.");
        }
        if (dryRun || "preview".equals(mode) || !smtpReady) {
            Files.createDirectories(outbox.getParent());
            Files.writeString(outbox, "To: %s%nSubject: %s%n%n%s".formatted(to.isBlank() ? "<APPROVAL_EMAIL_TO>" : to, subject, body));
            System.out.println("Email notification preview written to " + outbox);
            return false;
        }

        Properties properties = new Properties();
        properties.put("mail.smtp.auth", !username.isBlank());
        properties.put("mail.smtp.starttls.enable", "true");
        properties.put("mail.smtp.host", host);
        properties.put("mail.smtp.port", port);

        Session session = Session.getInstance(properties, new jakarta.mail.Authenticator() {
            @Override
            protected PasswordAuthentication getPasswordAuthentication() {
                return new PasswordAuthentication(username, password);
            }
        });

        Message message = new MimeMessage(session);
        message.setFrom(new InternetAddress(from));
        message.setRecipients(Message.RecipientType.TO, InternetAddress.parse(to));
        message.setSubject(subject);
        message.setText(body);
        Transport.send(message);
        System.out.println("Email notification sent to " + to);
        return true;
    }

    private static void audit(String region, String table, String eventType, String status, String message, String resource, boolean dryRun) {
        AuditWriter.put(region, table, "java-pr-approval-agent", eventType, status, "HUMAN_APPROVAL",
                "MEDIUM", resource, message, dryRun);
    }

    private static String emailBody(String project, String prUrl, String summary) {
        return """
                Human approval requested for %s.

                Summary:
                %s

                Review PR:
                %s

                Approve by merging the pull request. Deployment to ECS should proceed after approval.
                """.formatted(project, summary, prUrl);
    }

    private static String fallbackPrUrl(GitHubRepo repo, String branch) {
        return "https://github.com/%s/%s/pull/new/%s".formatted(repo.owner(), repo.name(), branch);
    }

    private static String htmlUrl(String json) {
        Matcher matcher = HTML_URL.matcher(json);
        if (!matcher.find()) {
            throw new IllegalStateException("Could not find html_url in GitHub response.");
        }
        return matcher.group(1).replace("\\/", "/");
    }

    private static AgentSupport.CommandResult run(Path repoDir, String... command) throws IOException, InterruptedException {
        return AgentSupport.run(repoDir, List.of(command), true);
    }

    private static String env(String name, String defaultValue) {
        String value = System.getenv(name);
        return value == null ? defaultValue : value;
    }

    private static String defaultBranch() {
        String stamp = DateTimeFormatter.ofPattern("yyyyMMddHHmmss").withZone(ZoneOffset.UTC).format(Instant.now());
        return "agent-fix-" + stamp;
    }

    private static String json(String value) {
        return "\"" + value.replace("\\", "\\\\").replace("\"", "\\\"").replace("\n", "\\n") + "\"";
    }

    private static String encode(String value) {
        return URLEncoder.encode(value, StandardCharsets.UTF_8);
    }

    private static String urlEncodeToken(String value) {
        return URLEncoder.encode(value, StandardCharsets.UTF_8).replace("+", "%20");
    }

    record GitHubRepo(String owner, String name) {
    }
}
